<?php
/**
 *
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Custom\HelloWorldRedirect\Controller\Adminhtml\Action;

/**
 * Class HelloWorld
 *  Custom\HelloWorldRedirect\Controller\Adminhtml\Action
 */
class Helloworld implements \Magento\Framework\App\ActionInterface
{
    /**
     * execute method
     */
    public function execute()
    {
        $this->_redirect('catalog/category/edit/id/38');
    }

    /**
     * Link must be generated by server side
     * It's only for education purpose!
     *
     * @return bool
     */
    public function _processUrlKeys()
    {
        return true;
    }
}
